- name: Create Directory /mnt/data/mysql for storage class on all nodes
  shell: |
    sudo mkdir -p /mnt/data/mysql && sudo chmod -R 777 /mnt/data/mysql
  creates: /mnt/data/mysql

- name: Generate kubeadm join command on the master node
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: "'masters' in group_names"
  changed_when: False

- name: Share join command with worker and proxy nodes
  set_fact:
    join_command: "{{ hostvars[groups['masters'][0]]['join_command_raw']['stdout'] | trim }}"
  when: inventory_hostname in groups['workers']
- name: Debug join command
  debug:
    msg: "Join command to be run: {{ join_command }}"
  when: inventory_hostname in groups['workers']

- name: Debug join command
  debug:
    msg: "Join command to be run: {{ join_command }}"
  when: inventory_hostname in groups['workers']

- name: Ensure TCP port 6443 on master is reachable
  wait_for:
    host: "{{ hostvars[groups['masters'][0]].ansible_host }}"
    port: 6443
    timeout: 10
  when: inventory_hostname in groups['workers']



- name: Reset the node if previously initialized
  shell: kubeadm reset -f && sudo rm -rf /etc/kubernetes /var/lib/etcd /var/lib/kubelet /home/eric/node_joined.log && systemctl restart kubelet
  args:
    chdir: /home/eric
  when: inventory_hostname in groups['workers']



- name: Join node to the cluster
  shell: "{{ join_command }} --ignore-preflight-errors=FileAvailable,Port >> /home/eric/node_joined.log"
  args:
    chdir: /home/eric
    creates: node_joined.log
  when: inventory_hostname in groups['workers']


