- name: Configure join commands on Master Nodes (Blue and Green).
  hosts: master-blue:master-green
  become: yes
  tasks:
    - name: Retrieve the join command.
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set the join command as a fact.
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Worker Nodes to respective clusters.
  hosts: workers-blue:workers-green
  become: yes
  tasks:
    - name: Identify respective master nodes.
      set_fact:
        master_node: "{{ 'master-blue' if 'workers-blue' in group_names else 'master-green' }}"

    - name: Ensure master node's port 6443 is accessible from workers.
      wait_for:
        host: "{{ groups[master_node][0] }}"
        port: 6443
        timeout: 1

    - name: Join worker nodes to their cluster.
      shell: "{{ hostvars[groups[master_node][0]].join_command }} >> node_joined.log"
      args:
        chdir: /home/eric
        creates: node_joined.log
